{
 "title": "Celery Monitoring",
 "description": "Monitor Celery Tasks with Prometheus and celery-exporter",
 "tags": [
  "prometheus",
  "celery"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": "label_values(celery_tasks_total,namespace)"
   },
   {
    "name": "Name",
    "query": "label_values(celery_tasks_total,name)"
   },
   {
    "name": "State",
    "query": "label_values(celery_tasks_total,state)"
   },
   { "name": "Interval", "query": "30s,1m,5m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Celery Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Celery Events by State rate (average $Interval)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum( rate(celery_tasks_total{namespace=~\"^$Namespace$\",name=~\"^$Name$\",state=~\"^$State$\"}[$Interval])  ) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Celery Events by Tasks rate (average $Interval)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{namespace=~\"^$Namespace$\", name=~\"^$Name$\", state=~\"^$State$\"}"
    }
   ]
  },
  {
   "title": "Celery Tasks runtime rate (average $Interval)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{namespace=~\"^$Namespace$\", name=~\"^$Name$\"}"
    }
   ]
  },
  {
   "title": "Celery Task latency rate (by $Interval)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{namespace=~\"^$Namespace$\", name=~\"^$Name$\"}"
    }
   ]
  },
  {
   "title": "Top Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 15 Tasks $State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "repeat": "State",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{namespace=~\"^$Namespace$\", name=~\"^$Name$\", state=~\"$State\"}"
    }
   ]
  }
 ]
}